### ISSUE TITLE
Captcha wird nicht mehr getriggert

### ISSUE THREAD

**Issue by hagengruber** [hagengruber/Burning-Series-Downloader#7]
Siehe:
https://www.firefox-forum.com/forum/thread/1492-bs-to-crawler-triggert-das-google-recaptcha-nicht-mehr/
https://support.mozilla.org/de/questions/1287974
https://www.python-forum.de/viewtopic.php?f=3&t=48630

**Comment by Liontix** [comment]
Hallo, ich kann dir den Grund nennen, warum die Captcha's nicht mehr getriggert werden, BS kann detecten, ob du eine normale Seleniuminstanz benutzt. Abhilfe schafft dabei https://github.com/ultrafunkamsterdam/undetected-chromedriver diese modifizierte Seleniumversion ermöglicht es einem die Captcha's wieder zu triggern.

**Comment by hagengruber** [comment]
@Liontix mit dem undetected-chromedriver funktioniert das Program wieder. Vielen Dank für deine Antwort!
